---
# Configuration file for MegaLinter

ENABLE_LINTERS:
  - YAML_PRETTIER
  - YAML_YAMLLINT
  - REPOSITORY_SECRETLINT
  - COPYPASTE_JSCPD
  - REPOSITORY_TRUFFLEHOG
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER

PRINT_ALL_FILES: false
APPLY_FIXES: all

SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: false
EMAIL_REPORTER: false

# FILTER_REGEX_EXCLUDE:
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
REPOSITORY_KICS_DISABLE_ERRORS: true
REPOSITORY_SECRETLINT_ARGUMENTS: --format compact
CLEAR_REPORT_FOLDER: true
